events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        http2 on;

        ssl_certificate /tmp/test.crt;
        ssl_certificate_key /tmp/test.key;

        location / {
            return 200 "HTTPS with copied certs!\n";
            add_header Content-Type text/plain;
        }
    }
}
