# version: "3.9"

services:
  backend-staging:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: idii-backend-staging
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.staging
    depends_on:
      - db-staging
    networks:
      - staging-network
    labels:
      - "environment=staging"
    command: >
      python -m uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
  personal-assistant-staging:
    build:
      context: ./backend/personal_assistant
      dockerfile: Dockerfile.prod
    container_name: idii-PA-staging
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - .env.staging
    depends_on:
      - db-staging
      - ollama-staging
    networks:
      - staging-network
    command: >
        python -m uvicorn main:app
        --host 0.0.0.0
        --port 8001
        --reload  

  frontend-staging:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_BACKEND_URL: http://${EXTERNAL_IP}:8000
        REACT_APP_PA_URL: http://${EXTERNAL_IP}:8001
        REACT_ENVIRONMENT: staging
    container_name: idii-frontend-staging
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    command: npm start

  db-staging:
    image: postgres:15
    container_name: idii-db-staging
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-productdb-staging}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-staging:/var/lib/postgresql/data
    networks:
      - staging-network

  ollama-staging:
    image: ollama/ollama:latest
    container_name: idii-ollama-staging
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      OLLAMA_ORIGINS: "${OLLAMA_ORIGINS:-*}"
      OLLAMA_HOST: "${OLLAMA_HOST:-0.0.0.0:11434}"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    volumes:
      - ./data/ollama-staging:/root/.ollama
    networks:
      - staging-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia 
              count: 1 
              capabilities: [gpu]
    runtime: nvidia
    # command: > 
    #   python -m uvicorn main:app
    #   --host 0.0.0.0
    #   --port 8001
    #   --reload

  nginx-staging:
    image: nginx:alpine
    container_name: idii-nginx-staging
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  
      - ./logs/nginx:/var/log/nginx

    depends_on:
      - frontend-staging
      - backend-staging
      - personal-assistant-staging

volumes:
  postgres_data:

networks:
  staging-network:
    driver: bridge
    name: idii-staging