version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: product-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: >
      python -m uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
  personal_assistant:
    build:
      context: ./backend/personal_assistant
      dockerfile: Dockerfile
      container_name: product_PA
      ports:
        - "8001:8001"
      env_file:
        - .env
      depends_on:
        - db
      volumes:
        - ./backend/personal_assistant:/app
      command: >
        python -m uvicorn main:app
        --host 0.0.0.0
        --port 8001
        --reload  

  frontend:
    build: ./frontend
    container_name: product-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    command: npm start

  db:
    image: postgres:15
    container_name: product-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-productdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: