"""
Base Resume Analyzer - Abstract Base Class

This module defines the abstract base class for resume analysis services.
Implementations can use different LLM providers (Ollama, vLLM, etc.) while
maintaining a consistent interface.

Design Pattern: Template Method + Abstract Factory
- Template Method: Common workflow logic (get resume, read content, store insights)
- Abstract Factory: Different LLM implementations (Ollama, vLLM)
"""

import os
import sys
import logging
from typing import Dict, Any, Optional, List
from abc import ABC, abstractmethod
import json

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..', '..')))

from backend.db.database import SessionLocal
from backend.utils.db_session import get_db_session, get_db_session_with_commit
from backend.models.resume import Resume
from backend.models.career_insight import CareerInsight
from backend.models.user import User
from backend.services.document_parser_service import DocumentParserService

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class BaseResumeAnalyzer(ABC):
    """
    Abstract base class for resume analysis services.

    This class defines the common interface and shared logic for resume analysis,
    regardless of the underlying LLM provider. Subclasses must implement the
    LLM-specific methods.

    Key Features:
    - Template method pattern for common workflows
    - Abstract methods for LLM-specific operations
    - Database operations (resume CRUD, insight storage)
    - Document parsing support (PDF, DOC, DOCX, TXT)
    - Intent detection for career insights
    - Dashboard summary extraction (summaries generated by workflow engine)
    """

    def __init__(self):
        """Initialize the base resume analyzer."""
        pass

    # ============================================================================
    # Abstract Methods - Must be implemented by subclasses
    # ============================================================================

    @abstractmethod
    async def _generate_llm_response(
        self,
        messages: List[Dict[str, str]],
        session_id: str = "default"
    ) -> str:
        """
        Generate LLM response for given messages.

        This is the core LLM interaction method that must be implemented
        by each provider-specific subclass.

        Args:
            messages: List of message dictionaries with 'role' and 'content'
            session_id: Session identifier for conversation tracking

        Returns:
            LLM-generated response text

        Note:
            - Ollama implementation: Uses chat_service._format_messages_for_ollama()
            - vLLM implementation: Uses direct LangChain ChatOpenAI.invoke()
        """
        pass

    @abstractmethod
    async def _extract_json_from_response(self, response_text: str) -> Dict[str, Any]:
        """
        Extract and parse JSON from LLM response.

        Different LLM providers may format JSON differently. This method
        handles provider-specific JSON extraction and validation.

        Args:
            response_text: Raw LLM response containing JSON

        Returns:
            Parsed JSON dictionary

        Raises:
            ValueError: If no valid JSON found in response
            json.JSONDecodeError: If JSON parsing fails
        """
        pass

    # ============================================================================
    # Template Methods - Shared workflow logic
    # ============================================================================

    async def detect_intent(self, user_message: str) -> str:
        """
        Detect if the user is requesting career insights.

        Args:
            user_message: The user's message

        Returns:
            'CAREER_INSIGHTS' or 'NORMAL_CONVERSATION'
        """
        try:
            from prompts import INTENT_DETECTION_PROMPT

            prompt = INTENT_DETECTION_PROMPT.format(user_message=user_message)
            messages = [{"role": "user", "content": prompt}]

            response_text = await self._generate_llm_response(messages, "intent_detection")
            intent = response_text.strip()

            # Normalize the response
            if "CAREER_INSIGHTS" in intent:
                return "CAREER_INSIGHTS"
            return "NORMAL_CONVERSATION"
        except Exception as e:
            logger.error(f"Error detecting intent: {str(e)}")
            return "NORMAL_CONVERSATION"  # Default to normal conversation on error

    async def analyze_resume(self, resume_content: str) -> Optional[Dict[str, Any]]:
        """
        Analyze resume content using LLM and extract structured information.

        This is the main analysis method that uses the LLM to parse and structure
        resume data. It uses the abstract _generate_llm_response method, making
        it provider-agnostic.

        Args:
            resume_content: The content of the resume

        Returns:
            A dictionary containing structured professional data or None if error
        """
        try:
            if not resume_content:
                return None

            import datetime
            from prompts import RESUME_ANALYSIS_SYSTEM_PROMPT, RESUME_ANALYSIS_PROMPT_TEMPLATE

            # Prepare the prompt with the resume content
            system_prompt = RESUME_ANALYSIS_SYSTEM_PROMPT

            current_date = datetime.datetime.now()
            current_year_month = f"{current_date.year}.{current_date.month:02d}"

            logger.info(f"Starting resume analysis (current date: {current_year_month})")

            prompt = RESUME_ANALYSIS_PROMPT_TEMPLATE.format(
                resume_content=resume_content,
                current_year=current_year_month
            )

            # Use the provider-specific LLM method
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ]

            # Generate response using abstract method
            response_text = await self._generate_llm_response(messages, "resume_analysis")

            logger.debug(f"LLM response length: {len(response_text)} characters")

            # Extract JSON using provider-specific method
            professional_data = await self._extract_json_from_response(response_text)

            logger.info("Resume analysis completed successfully")
            return professional_data

        except Exception as e:
            logger.error(f"Error analyzing resume: {str(e)}")
            return None

    # ============================================================================
    # Database Operations - Shared across all implementations
    # ============================================================================

    async def get_latest_resume(self, user_id: int) -> Optional[Resume]:
        """
        Get the most recently uploaded resume for a user.

        Args:
            user_id: The user's ID

        Returns:
            The most recent Resume object or None if not found
        """
        try:
            with get_db_session() as db:
                latest_resume = (
                    db.query(Resume)
                    .filter(Resume.user_id == user_id)
                    .order_by(Resume.created_at.desc())
                    .first()
                )
                return latest_resume
        except Exception as e:
            logger.error(f"Error getting latest resume: {str(e)}")
            return None

    async def get_resume_by_id(self, user_id: int, resume_id: int) -> Optional[Resume]:
        """
        Get a specific resume by ID for a user.

        Args:
            user_id: The user's ID
            resume_id: The specific resume ID

        Returns:
            The Resume object or None if not found
        """
        try:
            with get_db_session() as db:
                resume = (
                    db.query(Resume)
                    .filter(Resume.user_id == user_id, Resume.id == resume_id)
                    .first()
                )
                return resume
        except Exception as e:
            logger.error(f"Error getting resume by ID {resume_id}: {str(e)}")
            return None

    async def read_resume_content(self, resume: Resume) -> Optional[str]:
        """
        Read the content of a resume file using unified document parser.
        Supports PDF, DOC, DOCX, and TXT formats.

        Args:
            resume: The Resume object

        Returns:
            The content of the resume as a string, or None if error
        """
        try:
            if not resume or not resume.file_path:
                logger.error("Resume or file path is missing")
                return None

            file_path = resume.file_path

            # Check if file exists
            if not os.path.exists(file_path):
                logger.error(f"Resume file not found: {file_path}")
                return None

            # Check if format is supported
            if not DocumentParserService.is_supported_format(file_path):
                logger.warning(f"Unsupported file format: {file_path}")
                return None

            # Parse document using unified parser
            content = DocumentParserService.parse_document(file_path)

            if content:
                logger.info(f"Successfully read resume content from {file_path} ({len(content)} characters)")
                return content
            else:
                logger.warning(f"No content extracted from resume: {file_path}")
                return None

        except FileNotFoundError as e:
            logger.error(f"File not found: {str(e)}")
            return None
        except ValueError as e:
            logger.error(f"Invalid file format: {str(e)}")
            return None
        except Exception as e:
            logger.error(f"Error reading resume content: {str(e)}", exc_info=True)
            return None

    async def store_career_insight(
        self,
        user_id: int,
        resume_id: int,
        professional_data: Dict[str, Any]
    ) -> Optional[CareerInsight]:
        """
        Store the generated career insight in the database.

        Args:
            user_id: The user's ID
            resume_id: The resume's ID
            professional_data: The structured professional data

        Returns:
            The created CareerInsight object or None if error
        """
        try:
            with get_db_session_with_commit() as db:
                # Create a new career insight
                career_insight = CareerInsight(
                    user_id=user_id,
                    resume_id=resume_id
                )
                career_insight.set_professional_data(professional_data)

                # Add to database and flush to generate ID (but don't commit transaction yet)
                db.add(career_insight)
                db.flush()  # Generate ID without committing - allows refresh() to work
                db.refresh(career_insight)

                logger.info(f"Stored career insight for user {user_id}, resume {resume_id}")

                # Extract dashboard summaries from professional_data (already generated by vLLM)
                # The new single-stage workflow generates both full analysis AND summary in one call
                try:
                    summaries = {}
                    section_mapping = {
                        'professionalIdentity': 'professional_identity',
                        'educationBackground': 'education_background',
                        'workExperience': 'work_experience',
                        'skillsAnalysis': 'skills_analysis',
                        'marketPosition': 'market_position',
                        'salaryAnalysis': 'salary_analysis'
                    }

                    for data_key, summary_key in section_mapping.items():
                        summary_field = f"{data_key}_summary"
                        if summary_field in professional_data:
                            summaries[summary_key] = professional_data[summary_field]
                            logger.debug(f"Extracted summary for {summary_key}: {professional_data[summary_field][:50]}...")

                    if summaries:
                        career_insight.set_dashboard_summaries(summaries)
                        # No manual commit - let context manager handle it atomically
                        logger.info(f"Extracted and stored {len(summaries)} dashboard summaries for insight {career_insight.id}")
                    else:
                        logger.warning(f"No summaries found in professional_data for insight {career_insight.id}")
                except Exception as summary_error:
                    logger.warning(f"Failed to extract dashboard summaries: {summary_error}")
                    # Don't fail the main operation if summary extraction fails

                # Detach object from session before returning (prevents DetachedInstanceError)
                # All scalar attributes are already loaded, relationships remain unloaded
                db.expunge(career_insight)

                return career_insight
                # Context manager automatically commits all changes atomically on successful exit

        except Exception as e:
            logger.error(f"Error storing career insight: {str(e)}")
            return None

    async def get_latest_career_insight(self, user_id: int) -> Optional[Dict[str, Any]]:
        """
        Get the most recent career insight for a user.

        Args:
            user_id: The user's ID

        Returns:
            The professional data from the most recent career insight, or None if not found
        """
        try:
            with get_db_session() as db:
                latest_insight = (
                    db.query(CareerInsight)
                    .filter(CareerInsight.user_id == user_id)
                    .order_by(CareerInsight.created_at.desc())
                    .first()
                )

                if latest_insight:
                    return latest_insight.get_professional_data()
                return None

        except Exception as e:
            logger.error(f"Error getting latest career insight: {str(e)}")
            return None

    async def get_career_insight_by_resume(
        self,
        user_id: int,
        resume_id: int
    ) -> Optional[Dict[str, Any]]:
        """
        Get career insight for a specific resume.

        Args:
            user_id: The user's ID (for ownership verification)
            resume_id: The resume's ID

        Returns:
            The professional data from the career insight for the specified resume, or None if not found
        """
        try:
            with get_db_session() as db:
                career_insight = (
                    db.query(CareerInsight)
                    .filter(CareerInsight.user_id == user_id, CareerInsight.resume_id == resume_id)
                    .order_by(CareerInsight.created_at.desc())
                    .first()
                )

                if career_insight:
                    return career_insight.get_professional_data()
                return None

        except Exception as e:
            logger.error(f"Error getting career insight for resume {resume_id}: {str(e)}")
            return None

    # ============================================================================
    # High-Level Workflow Methods
    # ============================================================================

    async def process_user_message(self, user_message: str, user_id: int) -> Dict[str, Any]:
        """
        Process a user message and generate career insights if requested.

        This is the main entry point for user interactions. It detects intent,
        reads the resume, performs analysis, and stores insights.

        Args:
            user_message: The user's message
            user_id: The user's ID

        Returns:
            A dictionary containing the response type and data
        """
        try:
            # Detect if the user is requesting career insights
            intent = await self.detect_intent(user_message)
            logger.info(f"Detected intent: {intent}")

            if intent == "CAREER_INSIGHTS":
                # Get the latest resume
                latest_resume = await self.get_latest_resume(user_id)

                if not latest_resume:
                    return {
                        "type": "normal_response",
                        "message": "I couldn't find any uploaded resumes. Please upload your resume first."
                    }

                # Read the resume content
                resume_content = await self.read_resume_content(latest_resume)

                if not resume_content:
                    return {
                        "type": "normal_response",
                        "message": "I had trouble reading your resume. Please try uploading it again."
                    }

                # Analyze the resume
                professional_data = await self.analyze_resume(resume_content)

                if not professional_data:
                    return {
                        "type": "normal_response",
                        "message": "I encountered an issue analyzing your resume. Please try again later."
                    }

                # Store the career insight
                await self.store_career_insight(user_id, latest_resume.id, professional_data)

                # Return the professional data for display
                return {
                    "type": "career_insights",
                    "professional_data": professional_data,
                    "message": "I've analyzed your resume and generated career insights. You can view them in the Career Agent dashboard."
                }
            else:
                # For normal conversation, return None to indicate no special handling
                return {
                    "type": "normal_response",
                    "message": None  # Let the regular chat flow handle this
                }

        except Exception as e:
            logger.error(f"Error processing user message: {str(e)}")
            return {
                "type": "normal_response",
                "message": "I encountered an unexpected error. Please try again later."
            }

    # ============================================================================
    # Helper Methods - Shared formatting and utility functions
    # ============================================================================

    def _clean_json_string(self, json_str: str) -> str:
        """
        Clean and fix common JSON formatting issues in LLM responses.

        This method handles common JSON formatting problems that may occur in
        responses from both Ollama and vLLM (or any other LLM provider).

        Common issues fixed:
        - Trailing commas in objects and arrays
        - Unescaped quotes in strings
        - Extra whitespace
        - BOM markers or special characters
        - Unescaped newlines

        Args:
            json_str: Raw JSON string from LLM response

        Returns:
            Cleaned JSON string

        Note:
            This method is shared across all implementations. If provider-specific
            cleaning is needed, subclasses can override this method.
        """
        try:
            import re

            # Remove BOM and special characters
            json_str = json_str.strip()
            json_str = json_str.lstrip('\ufeff')  # Remove BOM (Byte Order Mark)

            # Fix trailing commas before closing braces and brackets
            json_str = re.sub(r',\s*}', '}', json_str)
            json_str = re.sub(r',\s*]', ']', json_str)

            # Fix unescaped newlines in strings
            json_str = re.sub(r'(?<!\\)\n', '\\n', json_str)

            logger.debug("[Base Resume Analyzer] JSON string cleaned")
            return json_str

        except Exception as e:
            logger.error(f"[Base Resume Analyzer] Error cleaning JSON string: {e}")
            # Return original if cleaning fails
            return json_str

    def _get_section_mapping(self, section_key: str) -> str:
        """Map summary section keys to professional data keys."""
        mapping = {
            'professional_identity': 'professionalIdentity',
            'education_background': 'educationBackground',
            'work_experience': 'workExperience',
            'skills_analysis': 'skillsAnalysis',
            'market_position': 'marketPosition',
            'salary_analysis': 'salaryAnalysis'
        }
        return mapping.get(section_key, section_key)

